#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4.1 on Thu May 04 01:45:25 2006

import wx

from system import GLSystem

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.window_1 = GLSystem(self.panel_1)
        self.label_4 = wx.StaticText(self, -1, "Forward Velocity")
        self.label_5 = wx.StaticText(self, -1, "Pitch Angle")
        self.label_6 = wx.StaticText(self, -1, "Yaw Angle")
        self.button_1 = wx.Button(self, -1, "Increase")
        self.button_2 = wx.Button(self, -1, "Decrease")
        self.button_3 = wx.Button(self, -1, "Increase")
        self.button_4 = wx.Button(self, -1, "Decrease")
        self.button_5 = wx.Button(self, -1, "Increase")
        self.button_6 = wx.Button(self, -1, "Decrease")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.IncreaseVelocity, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.DecreaseVelocity, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.IncreasePitch, self.button_3)
        self.Bind(wx.EVT_BUTTON, self.DecreasePitch, self.button_4)
        self.Bind(wx.EVT_BUTTON, self.IncreaseYaw, self.button_5)
        self.Bind(wx.EVT_BUTTON, self.DecreaseYaw, self.button_6)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.SetSize((475, 521))
        self.window_1.SetMinSize((462, 440))
        self.label_4.SetMinSize((80, 13))
        self.label_4.SetBackgroundColour(wx.Colour(236, 233, 216))
        self.label_5.SetBackgroundColour(wx.Colour(236, 233, 216))
        self.label_6.SetBackgroundColour(wx.Colour(236, 233, 216))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(2, 3, 1, 1)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.window_1, 1, wx.EXPAND, 0)
        self.panel_1.SetAutoLayout(True)
        self.panel_1.SetSizer(sizer_1)
        sizer_1.Fit(self.panel_1)
        sizer_1.SetSizeHints(self.panel_1)
        sizer_2.Add(self.panel_1, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_4, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_5, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_6, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(self.button_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(self.button_2, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_4.Add(self.button_3, 0, wx.ADJUST_MINSIZE, 0)
        sizer_4.Add(self.button_4, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_5.Add(self.button_5, 0, wx.ADJUST_MINSIZE, 0)
        sizer_5.Add(self.button_6, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_2.Add(grid_sizer_1, 0, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

    def IncreaseVelocity(self, event): # wxGlade: MyFrame.<event_handler>
        self.window_1.DoCameraChange(0, -.1)
        event.Skip()

    def DecreaseVelocity(self, event): # wxGlade: MyFrame.<event_handler>
        self.window_1.DoCameraChange(0, .1)
        event.Skip()

    def IncreasePitch(self, event): # wxGlade: MyFrame.<event_handler>
        self.window_1.DoCameraChange(1, .2)
        event.Skip()

    def DecreasePitch(self, event): # wxGlade: MyFrame.<event_handler>
        self.window_1.DoCameraChange(1, -.2)
        event.Skip()

    def IncreaseYaw(self, event): # wxGlade: MyFrame.<event_handler>
        self.window_1.DoCameraChange(2, .1)
        event.Skip()

    def DecreaseYaw(self, event): # wxGlade: MyFrame.<event_handler>
        self.window_1.DoCameraChange(2, -.1)
        event.Skip()

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
